In [1]:
import numpy as np

In [2]:
A = np.array([[3,1,np.nan],[1,1,-2],[np.nan, -2, 6]])
A

array([[ 3.,  1., nan],
       [ 1.,  1., -2.],
       [nan, -2.,  6.]])

In [12]:
Q = np.isnan(A)
_Q = np.invert(Q).astype(np.float64)

In [74]:
def get_U(X):
    k = 2
    u, s, vh = np.linalg.svd(X)
    s[k-1:] = 0
    return u.dot(np.diag(s)).dot(vh)

In [78]:
e = 1e-6
X = np.nan_to_num(A)
j = 0
while True:
    j += 1
    X_ = np.copy(X)
    X_k = get_U(X)
    for i in np.argwhere(np.isnan(A)):
        X[i] = X_k[i]
    print(j, np.linalg.norm(X - X_))
    if np.linalg.norm(X - X_) < e:
        break  
    
    

1 3.1605210015232825
2 0.27064799560517294
3 0.24039015680115272
4 0.21241728905366056
5 0.18694752132734074
6 0.1640219617249845
7 0.14356500928604446
8 0.1254303693858353
9 0.10943403566988656
10 0.09537672167615648
11 0.08305835702678815
12 0.07228691534257793
13 0.06288335400071955
14 0.05468398063068468
15 0.04754117755142581
16 0.04132312293981159
17 0.03591293541253065
18 0.031207519983666165
19 0.027116291683371693
20 0.023559885011021294
21 0.020468912589086348
22 0.017782807437059362
23 0.015448764961626293
24 0.01342078945643348
25 0.011658843181854821
26 0.010128092319246097
27 0.008798242185117941
28 0.007642953339436559
29 0.006639330168761621
30 0.0057674738733034595
31 0.00501009234941597
32 0.004352160118510958
33 0.0037806221384960887
34 0.003284136002703512
35 0.0028528476606762923
36 0.0024781963736591897
37 0.0021527451410265326
38 0.001870033302097733
39 0.0016244484336080912
40 0.0014111150300335769
41 0.0012257977766850247
42 0.0010648175082848667
43 0.000924978

In [79]:
X_

array([[ 0.25103513,  0.25103564, -0.50207179],
       [ 1.        ,  1.        , -2.        ],
       [-2.55959242, -2.55959764,  5.11920051]])

In [38]:
e_val, e_vec = np.linalg.eig(X)
i_rev = e_val.argsort()[::-1]
eig_vals = e_val[i_rev]
eig_vecs = e_vec[:, i_rev]

In [34]:
k = 2
eig_vecs[:,k:] = 0
U = eig_vecs

In [35]:
X_k = X.dot(U)

In [36]:
X_k

array([[-0.61741222, -3.10141938,  0.        ],
       [-2.30421377, -0.83102282,  0.        ],
       [ 6.29522908, -0.60835092,  0.        ]])

In [102]:
u, s, vh = np.linalg.svd(X - X.mean(0))

In [3]:
X = np.nan_to_num(A)

In [103]:
u, s, v = np.linalg.svd(X - X.mean(0))

In [105]:
s[2:] = 0
np.diag(s)

array([[6.4965992 , 0.        , 0.        ],
       [0.        , 1.76848301, 0.        ],
       [0.        , 0.        , 0.        ]])

In [107]:
X_ = u.dot(np.diag(s)).dot(v)

In [112]:
A - np.nanmean(A, 0)

array([[ 1.,  1., nan],
       [-1.,  1., -4.],
       [nan, -2.,  4.]])

In [8]:
A_

array([[ 3.,  1.,  0.],
       [ 1.,  1., -2.],
       [ 0., -2.,  6.]])

In [5]:
for i in np.arange(-6.0, 6.0, 0.5):
    print(i)
    X = np.nan_to_num(A, nan=i)
    print(np.linalg.eig(X)[0])

-6.0
[11.15829251 -1.76693569  0.60864318]
-5.5
[10.69902639 -1.2946363   0.5956099 ]
-5.0
[10.24518502 -0.83186189  0.58667687]
-4.5
[ 9.79795375 -0.38871707  0.59076332]
-4.0
[9.35889894e+00 6.41101056e-01 2.42106856e-16]
-3.5
[8.93013558 0.83524338 0.23462104]
-3.0
[8.51458909 1.18910769 0.29630322]
-2.5
[8.11641249 1.59367464 0.28991287]
-2.0
[7.74165739 2.         0.25834261]
-1.5
[7.39933374 2.38848012 0.21218614]
-1.0
[7.10294086 2.7430865  0.15397264]
-0.5
[6.87207209 3.04427789 0.08365002]
0.0
[0.         3.26794919 6.73205081]
0.5
[-0.09890613  3.39170382  6.70720231]
1.0
[-0.21550352  3.40844276  6.80706076]
1.5
[-0.35256485  3.334015    7.01854985]
2.0
[-0.51297605  3.19790564  7.31507041]
2.5
[ 7.67048495  3.02893837 -0.69942332]
3.0
[ 8.06533254  2.8486819  -0.91401445]
3.5
[ 8.48667701  2.6712424  -1.15791941]
4.0
[ 8.92620019  2.50494808 -1.43114826]
4.5
[ 9.37853129 -1.73255211  2.35402083]
5.0
[ 9.84013339 -2.06004288  2.21990949]
5.5
[10.30861803 -2.41094056  2.10232